services:
  expense-api:
    build: ./expense-api
    ports:
      - "8000:8000"
    env_file:
      - ./expense-api/.env
    volumes:
      - /home/shubham/service-account-key.json:/app/service_account.json:ro
    environment:
      - GOOGLE_SERVICE_ACCOUNT_FILE=/app/service_account.json

  expense-mcp:
    build: ./expense-mcp
    ports:
      - "8001:8001"
    environment:
      - API_BASE_URL=http://expense-api:8000
    depends_on:
      - expense-api
